spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true

#spring:
#  config:
#    activate:
#      on-profile: mysql
#  datasource:
#    url: jdbc:mysql://localhost:3306/commerce?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    username: test
#    password: 1234
#  jpa:
#    database-platform: org.hibernate.dialect.MySQL8Dialect
